//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE_DB.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_conformity
    {
        public decimal ID_Dictionary_conformity { get; set; }
        public Nullable<decimal> ID_Vocabulary_entry { get; set; }
        public Nullable<decimal> Number_string { get; set; }
        public Nullable<decimal> ID_Language { get; set; }
        public string Phorma { get; set; }
        public string Variant { get; set; }
        public string p_00 { get; set; }
        public string p_1 { get; set; }
        public string p_2 { get; set; }
        public string p_3 { get; set; }
        public string p_4 { get; set; }
        public string p_5 { get; set; }
        public string p_6 { get; set; }
        public string p_7 { get; set; }
        public string p_8 { get; set; }
        public string p_9 { get; set; }
        public string p_10 { get; set; }
        public string p_11 { get; set; }
        public string p_0 { get; set; }
        public string Meaning { get; set; }
        public string Comment { get; set; }
        public string Link { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Vocabulary_entry Vocabulary_entry { get; set; }
    }
}
