//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE_DB.Data_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIE_Entities : DbContext
    {
        public PIE_Entities()
            : base("name=PIE_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Dictionary_conformity> Dictionary_conformity { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Phoneme> Phoneme { get; set; }
        public virtual DbSet<Phonetic_matching> Phonetic_matching { get; set; }
        public virtual DbSet<Rule> Rule { get; set; }
        public virtual DbSet<Vocabulary_entry> Vocabulary_entry { get; set; }
    }
}
