//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIE_DB.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary_entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vocabulary_entry()
        {
            this.Dictionary_conformity = new HashSet<Dictionary_conformity>();
        }
    
        public decimal ID_Vocabulary_entry { get; set; }
        public Nullable<decimal> Number_vocabulary_entry { get; set; }
        public string Lemma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dictionary_conformity> Dictionary_conformity { get; set; }
    }
}
